### ISSUE TITLE
Update the current repository to point to latest stable release

### ISSUE THREAD

**Issue by mannykoum** [infiniteorbits/hart-software-services#1]

**Comment by mannykoum** [comment]
Already at latest but the tags have not been sync'ed

**Comment by abelixrev** [comment]
We are closing this ticket because the issue of updating the current repository to the latest stable release is already being addressed comprehensively in ticket #4 (Update HSS to latest version). All relevant actions and updates are being tracked and managed under that ticket. This includes updating the HSS version, addressing specific boot issues, and validating the changes on relevant hardware.

To avoid duplication of efforts and to streamline our tracking process, we will continue all related discussions and updates in ticket #4.
